apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eldewrito.fullname" . }}
  labels:
    {{- include "eldewrito.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "eldewrito.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eldewrito.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eldewrito.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUN_AS_USER
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: dewrito-prefs
              mountPath: /tmp/dewrito_prefs.cfg
              readOnly: true
            - name: game
              mountPath: /game
            - name: logs
              mountPath: /logs
          ports:
            - containerPort: 11774
              protocol: UDP
              hostPort: 11774
            - containerPort: 11775
              hostPort: 11775
              protocol: TCP
            - containerPort: 11776
              protocol: TCP
              hostPort: 11776
            - containerPort: 11777
              protocol: TCP
              hostPort: 11777
      volumes:
        - name: config
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: {{ template "eldewrito.fullname" . }}-veto
              - configMap:
                  name: {{ template "eldewrito.fullname" . }}-voting
        - name: dewrito-prefs
          configMap:
            defaultMode: 420
            name: {{ template "eldewrito.fullname" . }}-dewrito-prefs
            items:
              - key: dewrito_prefs.cfg
                path: dewrito_prefs.cfg
        - name: game
          hostPath:
            path: /srv/eldewrito/game
            type: Directory
        - name: logs
          hostPath:
            path: /srv/eldewrito/logs
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
