{{- if .Values.webserver.ingress.enabled -}}
{{- $fullName := include "static-site.fullname" . -}}
{{- $svcPort := .Values.webserver.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
  {{- with .Values.webserver.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.webserver.ingress.tls }}
  tls:
  {{- range .Values.webserver.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.webserver.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  name: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
