replicaCount: 1

image:
  repository: domistyle/eldewrito
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
      - SYS_PTRACE

resources:
  limits:
    cpu: 1
    # memory: 4Gi
  requests:
    cpu: 1
    # memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
